[package]
name = "rust-webgl-engine-boilerplate"
version = "0.1.0"
authors = ["ibaryshnikov <baryshnikov.il@gmail.com>"]
edition = "2018"

crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3.10"
wasm-bindgen = "0.2.33"
web-sys = "0.3.10"
